# https://docs.docker.com/compose/compose-file/compose-versioning/#version-38
version: '3.8'
services:
  db:
    image: mysql:8.0.29
    # caching_sha2_passwordから旧来のmysql_native_passwordへ変更
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - 3306:3306
